//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoJudo.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group()
        {
            this.ParticipantCompetitions = new HashSet<ParticipantCompetition>();
        }
    
        public int Id { get; set; }
        public int IdCompetition { get; set; }
        public int IdWeightCategory { get; set; }
        public int IdAgeCategory { get; set; }
        public string GenderCategory { get; set; }
    
        public virtual AgeCategory AgeCategory { get; set; }
        public virtual Competition Competition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipantCompetition> ParticipantCompetitions { get; set; }
        public virtual WeightCategory WeightCategory { get; set; }
    }
}
