//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoJudo.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryLogin
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public System.DateTime DateTimeLogin { get; set; }
        public System.DateTime DateTimeExit { get; set; }
    
        public virtual User User { get; set; }
    }
}
